version: '3.9'

services:

  db:
    image: postgres:16.2
    container_name: pomodoro-db
    restart: always
    shm_size: 128
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pomodoro