"""add_asd_tasks

Revision ID: 312352f650e1
Revises: 891ca44db146
Create Date: 2024-09-29 10:04:03.813936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312352f650e1'
down_revision: Union[str, None] = '891ca44db146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('asd', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'asd')
    # ### end Alembic commands ###
